DROP TABLE SAE_CONTRAT_LOCATAIRE;
DROP TABLE SAE_FACTURE;
DROP TABLE SAE_COMPTEUR;
DROP TABLE SAE_ASSURANCE;
DROP TABLE SAE_ENTREPRISE;
DROP TABLE SAE_PAIEMENT;
DROP TABLE SAE_IRL;
DROP TABLE SAE_DIAGNOSTICS;
DROP TABLE SAE_CHARGES_GENERALE;
DROP TABLE SAE_CONTRATLOCATION;
DROP TABLE SAE_LOCATAIRE;
DROP TABLE SAE_BIENLOUABLE;
DROP TABLE SAE_BATIMENT;
DROP TABLE SAE_GARANT;

SET AUTOCOMMIT ON;
SHOW AUTOCOMMIT;    